#
# Copyright 2016-2020 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Build and Verify

on: [ pull_request]

jobs:
    build-and-verify:
      runs-on: ubuntu-latest
      timeout-minutes: 40
      env:
        NODE_VERSION: 14.17.1
        SPRING_OUTPUT_ANSI_ENABLED: DETECT
        SPRING_JPA_SHOW_SQL: false
        JHI_DISABLE_WEBPACK_LOGS: true
        NG_CLI_ANALYTICS: false      
      steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive      
      - uses: actions/setup-node@v1
        with:
          node-version: 14.17.1      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Install node.js packages
        run: npm install          
      - name: Cache Maven archetypes
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Install submodule
        working-directory: ./hapi-fhir-jpaserver-starter
        run: |
          mvn install -DskipTests
          mvn install:install-file -Dfile=target/ROOT-classes.jar -DgroupId=ca.uhn.hapi.fhir -DartifactId=hapi-fhir-jpaserver-starter -Dversion=5.7.0 -Dpackaging=jar             
      - name: Verify backend
        run: mvn verify
      - name: Run frontend test
        working-directory: ./open-health-manager-app
        run: npm run ci:frontend:test        